var _dir="/tpl/";
//document.write("<script src='/assets/javascripts/jquery/jquery-migrate.min.js' type='text/javascript'></script>");
//document.write("<script src='/assets/javascripts/plugins/datatables/colResizable-1.5.min.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/plugins/laydate5.0/laydate.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/plugins/select2/select2.full.min.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/json2.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/api/e.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/api/JSONFormat.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/dqq_request.js' type='text/javascript'></script>");
document.write("<script src='/assets/javascripts/dqq_form.js' type='text/javascript'></script>");
